apiVersion: v1
kind: Service
metadata:
  name: dogreponook
  labels:
    app: dogreponook
spec:
  type: LoadBalancer
  selector:
    app: dogreponook
  ports:
    - port: 8191
      targetPort: 80
      protocol: TCP
      name: http

