apiVersion: v1
kind: Service
metadata:
  name: dogreponook-svc
  labels:
    app: dogreponook-svc
spec:
  type: LoadBalancer
  ports:
    - port: 8191
      targetPort: dogrepo-port
      protocol: TCP
      name: http
  selector:
    app: dogreponook
