apiVersion: apps/v1
kind: Deployment
metadata:
  name: dogreponook
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dogreponook
  template:
    metadata:
      labels:
        app: dogreponook
    spec:
      containers:
      - name: dogreponook-pod
        image: docker.io/mtmazurik/devopsgenie-reponook:latest
        imagePullPolicy: Always
        ports:
        - name: dogrepo-port
          containerPort: 80
        livenessProbe:
          httpGet:
            path: /admin/ping
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 30
        readinessProbe:
          httpGet:
            path: /admin/ping
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 30


