FROM microsoft/dotnet:2.2-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 80

FROM microsoft/dotnet:2.2-sdk AS build
WORKDIR /src
COPY DOG.RepoNook.csproj ./
RUN dotnet restore DOG.RepoNook.csproj
COPY . ./
RUN dotnet build DOG.RepoNook.csproj -c Release -o /app

FROM build AS publish
RUN dotnet publish DOG.RepoNook.csproj -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "DOG.RepoNook.dll"]
