apiVersion: v1
kind: Service
metadata:
    name: "akscluster"
    labels:
        app: "akscluster"
spec:
    type: LoadBalancer
    ports:
    - port: 81
      targetPort: http
      protocol: TCP
      name: http
    selector:
        app: "akscluster"